health_check_path: "/healthz"
port: 8000
brokers:
  - name: "broker1"
    host: "http://broker1:8080"
  - name: "broker2"
    host: "http://broker2:8080"
  - name: "broker3"
    host: "http://broker2:8080"
replica: 2
postgres:
  host: "postgres-zookeeper"
  port: 5432
  dbname: "postgres"
  user: "postgres"
  password: "postgres"
